const FETCH_FOOTBALL_PLAYERS_SUCCESS = 'FETCH_FOOTBALL_PLAYERS_SUCCESS';
const FILTER_FOOTBALL_PLAYERS = 'FILTER_FOOTBALL_PLAYERS';

export {
  FETCH_FOOTBALL_PLAYERS_SUCCESS,
  FILTER_FOOTBALL_PLAYERS,
};
